# Generated by Django 5.1 on 2024-09-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
